name: google_tag_manager
description: Dart wrapper around google tag manager js api
version: 0.0.2
homepage: https://lefty.io
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1

dev_dependencies:
  test: ^0.12.0
